# Generated by Django 3.2.5 on 2022-02-18 15:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todoform',
            fields=[
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('stamp', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
