# Generated by Django 3.2.5 on 2022-02-18 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoUsers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
